### ISSUE TITLE
Trigger Mailman on formsubmit

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/Mailman#105]
Mailman could be improved by having repeated merges send onFormSubmit. Requested by matthew.raven@edmonton.ca.

**Comment by j-rewerts** [comment]
Google Apps Script allows you to tie into form submission requests. The event is detailed [here](https://developers.google.com/apps-script/guides/triggers/events). Currently, Mailman uses a timed event to trigger the mail merge. This can be done once per hour at most. Since many users use Mailman to send emails based on info that comes from a Google Form, onFormSubmit could be a good way to make Mailman more regular.

**Comment by dchenier** [comment]
To clarify, the mail merge would only run for the rows submitted, right?

**Comment by j-rewerts** [comment]
I haven't been totally won over either way on this. It could be nice to make it work globally, but that may add more headaches then we really want.

**Comment by dchenier** [comment]
Hmm...wouldn't it be awkward to resend emails over rows that already had emails sent out?

I'm think the use case would be something like sending an email acknowledging receipt of a form...we wouldn't want to do that multiple times, right?

**Comment by j-rewerts** [comment]
Ya, you're probably right. Can't really think of a valid use case for running through all.

**Comment by dchenier** [comment]
But then how does the repeater work? Does it fire multiple times for a row or does it only do the rows it hasn't done yet?

**Comment by dchenier** [comment]
This was implemented between Aug - Sept over several commits....Will be released in the next version being released end of Sept 2018.
