### ISSUE TITLE
Embedded buttons and fields

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/Mailman#148]
A neat idea for Mailman to have would be a free form (but VERY simple) gui elements system. Before the MergeTag swapping pass, it would swap out things like <<!Button!>> with an actul button or <<!Input!>> with a text entry field. 

The crappy thing about this would be the fact that just supporting HTML would be far more powerful. 

I got the idea from YAMM. See their [blog post](url) about it.

**Comment by dchenier** [comment]
As of Dec 2017 Rich Text Mailman now supports HTML editing
