### ISSUE TITLE
TypeError: Cannot call method "getDataRange" of null. at [unknown function](email-service:40) at exposeRun(expose-run:11)

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/Mailman#151]

**Comment by dchenier** [comment]
Steps to reproduce?

**Comment by dchenier** [comment]
Not enough info, and likely not an issue in Rich Text Mailman as the rendering is completely different.

**Comment by j-rewerts** [comment]
My bad. I'll try to add more details in the future. 

This was an issue I created after noticing it happening in StackDriver. Never could repro it. I'll be sure to add steps in the future.
