### ISSUE TITLE
User feedback from danny.edwards@edmonton.ca

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/Mailman#156]
HI Jared. I am working on the Windows 10 Upgrade project, and based on the functionality and improvement to a few of our processes (UAT, App Sign Off, Licensing) we are looking at using Mailman as our defacto communication tool for all City of Edmonton users. 

In the communications we send out though, we need to format certain pieces of the email (i.e. highlight a line in yellow, bold some text, etc) to explain to users that it's an important piece of text they shouldn't overlook. 

Hence, the need for formatting options within mailman. 

Thanks

**Comment by j-rewerts** [comment]
Related to #104 .

**Comment by j-rewerts** [comment]
It's important that the API for this is the same as for a normal mail merge, or for sending a Form, such as in #162 .

**Comment by j-rewerts** [comment]
#174 may end up providing a better solution for this than merge from Doc.

**Comment by dchenier** [comment]
Rich text functionality is now provided by a built in rich text editor (TinyMCE).
