### ISSUE TITLE
Shaylen Naidoo: Conditional Send Should Support More Than Just TRUE/FALSE

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/Mailman#167]
**Email**
shaylen.naidoo@edmonton.ca

**Description**
Please change the conditional send to be "User Defined" ie. use a word of choice "Yes", "No", etc. We can then configure multiple conditions and use the same sheet and column to drive multiple mail merges.

**Comment by dchenier** [comment]
Rich Text Mailman now support "TRUE"/"Yes" and "FALSE"/"No"
