### ISSUE TITLE
Add a linter

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/Mailman#17]
Google uses Closure Linter

**Comment by stvhwrd** [comment]
Will need **[Closure Linter](https://developers.google.com/closure/utilities/)** installed locally (on dev machine), which can be run directly from CLI:

eg.
> To run the Closure Linter on a single file:
> 
> `$ gjslint path/to/my/file.js `

Ideally, we'll use **[gulp-gjslint](https://www.npmjs.com/package/gulp-gjslint)** in our existing gulpfile to lint during the build process, and *potentially* (version compatibility is iffy ATOW) use **[linter-gjslint](https://github.com/kolomiichenko/linter-gjslint)** with the base linting package **[Linter](https://github.com/steelbrain/linter)** for linting during development in Atom.
