### ISSUE TITLE
Explore advanced Doc to HTML conversion

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/Mailman#175]
A company called cloudHQ has an extension that [converts Docs to Gmail](https://chrome.google.com/webstore/detail/convert-google-docs-to-gm/dingigiembmnbjocifcoeiideggpkplj). This must mean it is possible to have nicely formatted emails from Google Docs.

**Comment by j-rewerts** [comment]
I've been able to create solid looking emails now. 
![image](https://user-images.githubusercontent.com/8295080/31405882-8fb49b36-adbc-11e7-948e-fd1c4622e231.png)

**Comment by dchenier** [comment]
Rich text functionality is now provided by a built in rich text editor (TinyMCE).
