### ISSUE TITLE
Fix HTML local storage block issue

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/Mailman#176]
Danny Edwards wasn't able to open Mailman due to Chrome blocking HTML local storage. I have to figure out a way to request access from users.

**Comment by j-rewerts** [comment]
![image](https://user-images.githubusercontent.com/8295080/31399382-5228068a-ada9-11e7-9f5b-4c076e0e99c6.png)

**Comment by dchenier** [comment]
Fixed with Rich Text mailman, which uses a new browser window and [window.postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) rather than the chrome addon dialog boxes with localstorage for communication
