### ISSUE TITLE
Dates are not formatted

### ISSUE THREAD

**Issue by dchenier** [coe-google-apps-support/Mailman#181]
Referencing a date from a Google sheet like <<MyDateColumn>> results in a value such as: Wed Dec 06 2017 08:04:32 GMT-0700 (MST)

There should be the ability to format dates to more presentable forms, such as short date with no time, other other formats.

Issue originates from a conversation between Danny Edwards and Dan Chenier Dec 6 2017.

**Comment by j-rewerts** [comment]
I could be wrong about this, but I think I looked into this and it's actually Google Sheets that determines how the date is formatted? Does using Format > Numbers > More formats change the way Mailman ends up sending the date?

**Comment by dchenier** [comment]
Hmmm... Looks like I changed the behaviour when I implemented the handlebars rendering over the old regex/replace method before.

i.e. the relevant line used to be: `var emailProps = EmailService.getEmailFields(header, row.**getDisplayValues()**[0], template);`
and now's it's essentially `sheet.**getSheetValues**(rowNum, 1, 1, 128)[0];`

There is value in taking the actual object now though, because we can use the handlebars engine to format values in the template itself.  e.g. {{formatDate MyDateColumn "MMMM dd yyyy"}}. More importantly, [getDisplayValue()](https://developers.google.com/apps-script/reference/spreadsheet/range#getDisplayValue()) always returns a string, whereas [getSheetValues](https://developers.google.com/apps-script/reference/spreadsheet/sheet#getsheetvaluesstartrow-startcolumn-numrows-numcolumns) returns the type in the cell.  So we'll be able to do things like {{ sum (range "Sheet!A1:A100") }}

**Comment by dchenier** [comment]
I suppose another consequence of using the raw values would be 
e.g. a column is formatted with a percentage a a cell has a value of 0.2%.  The rich text mailman would likely output 0.002 as a number.  Probably not what users would expect.

But as mentioned in previous comment I still think there's value in having access to the raw values.  We can probably provide both on the context.  i.e. **{{ MyDateField }}** should show the formatted date but maybe we could do **{{ _rawValues.MyDateField }}** or something like that to get to the raw values. So then if we wanted to format it differently we could do something like **{{ formatDate _rawValues.MyDateField "MMM dd yyyy hh:mm:ss a" }}**

**Comment by j-rewerts** [comment]
Oh right. Yes I remember solving this now. I think what I found was getDisplayValue always returns pretty much exactly what is shown in the cell. getValues returns an actual object, so for a Date object, you have to format yourself.

Not a bad idea about exposing the objects though. Especially now that we're allowing more advanced processing with Handlebars.

**Comment by dchenier** [comment]
Changed handlebars context to use display values rather than raw values, as the original Mailman did.
