### ISSUE TITLE
Repeater icon onmousehover should stay as a pointer

### ISSUE THREAD

**Issue by dchenier** [coe-google-apps-support/Mailman#202]
When you hover the mouse over the repeater icon on the main mailman page, the mouse cursor is a little hand, implying that the icon can be clicked.  Since we can't click it anymore, we should leave the mouse cursor as a pointer.
![image](https://user-images.githubusercontent.com/31138373/44918924-6704c480-acf9-11e8-956b-f238dc69de1e.png)

**Comment by Zhipeng-Chang** [comment]
fixed
