### ISSUE TITLE
Implement merge "triggers"

### ISSUE THREAD

**Issue by dchenier** [coe-google-apps-support/Mailman#256]
Mailman 2.0 needs to run mergeTemplates based on triggers, like the old mailman.

Currently, Mailman 2.0 has OAuth tokens that are only good for each request that the client sends to the backend (because "refresh tokens" are never supplied to our backend).  In order to run merge templates at any arbitrary time, we'll need up to date OAuth tokens when we run the merge templates.

There are 2 ways we can achieve this:

1. We can use Appscript triggers to call our backend services.  When calling the services, we can send updated tokens at that time because our users will have given consent to the appscript to run on their behalf.  This way has many of the same limitations as the old Mailman (i.e. max every 15 minutes), however it won't be limited by running for 6 minutes as the backend can do the heavy lifting.

2. We can have our new implementation ask for OAuth consent again. By doing this, we can get a refresh token, store it in our database and use it whenever we need to get an up to date access token.  This approach is the most flexible however it makes our users get 2 consent screens when they install our app.

**Comment by j-rewerts** [comment]
I like 2 also. I think we really need refresh tokens. A side benefit of this is that we'll be less dependant on Google Apps Script. Our first prompt will have really minimal scopes (I'm actually not too sure what we'll even be asking for here). Our second will have a bunch of Drive, Sheets, GMail and other scopes.

**Comment by j-rewerts** [comment]
I'm thinking of changing the experience so we store the user object in our client app. If the user doesn't exist, it'll show a log in with Google button, which will launch our OAuth flow.

I like this approach, since it'll be the same when it's ran as an add-on or as a standalone web app.

**Comment by dchenier** [comment]
That all makes sense to me, and makes our whole OAuth token management easier to get them all from one place instead of two.

**Comment by j-rewerts** [comment]
I have a controversial idea that we haven't dove into much. What if we removed merge triggers altogether from Mailman? It was the reason I built it in the first place, but it just isn't used much. If I can get Danny Edwards to okay it, I think it could be a good thing.
