### ISSUE TITLE
Create a mock up for the new UI

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/Mailman#27]

**Comment by stvhwrd** [comment]
* Scratch pad "[Mailman mockup](https://www.draw.io/#G0B81hTXqYXLksQTFOc3huRVdsOUE)" on draw.io.  

* Desired <<tag>> autocompletion might be achieved using [jQuery UI's Autocomplete widget](https://jqueryui.com/autocomplete/)

**Comment by j-rewerts** [comment]
This is mostly done. The prototype is underway (#32).

**Comment by j-rewerts** [comment]
@stvhwrd You think this is good to close?
