### ISSUE TITLE
Project must be built twice to work

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/Mailman#50]
If you use the Gulp clean task, then the Gulp build-web or build-gas task, the project won't yet work. It has to be built twice for some reason.

**Comment by stvhwrd** [comment]
@j-rewerts has suggested that the problem may lie in the sequence ordering of individual gulp tasks, such that out-of-order operations do not properly satisfy in-builld dependencies.  This would explain why the second build works where the first does not.

**Comment by j-rewerts** [comment]
Totally stole this issue from @stvhwrd . I just type so(oooooo) much faster.

**Comment by stvhwrd** [comment]
## ಠ_ಠ

**Comment by j-rewerts** [comment]
:smiley:
